task_breakdown:
  description: >
    Carefully analyze the {project_requirements}for the {project_type} project and break them into individual tasks. Define each task's scope in detail, set achievable timelines, and ensuer that all dependencies are accounted for:

    {project_requirements}

    Team members:

    {team_members}
  expected_output: >
    A comprehensive list of tasks with detailed descriptions, timelines, dependencies, and deliverables. Your final output MUST include a Gantt chart or similar timeline visualization specific to the {project_type} project.

time_resource_estimation:
  description: >
    Thoroughly evaluate each task in the {project_type} project to estimate the time, resources and effort required. Use historical data, task complexity, and available resources to provide a realistic estimation of each tasks.
  expected_output: >
    A detailed estimation report outlining the time, resources, and effort required for each task in the {project_type} project. Your final report MUST include a summary of any risks or uncertainties associated with the estimations.

resource_allocation:
  description: >
    Analyze the detailed task breakdown and time/resource estimations for the {project_type} project. Develop a strategic resource allocation plan by assigning {team_members}, and equipment to each task. Ensure the allocation is balanced to avoid bottlenecks, addresses all dependencies, and maximizes efficiency to meet {project_objective} while staying within budget. Factor in skill levels, availability of resources, and any constraints from {project_requirements} to optimize the allocation.

  expected_output: >
